server:
    port: 80
    compression:
        min-response-size: 512
        enabled: true
        mime-types: text/html,text/css,text/javascript,application/javascript,image/gif,image/png,image/jpg
    tomcat:
      maxThreads: 20
      minSpareThreads: 3
      accesslog:
        directory: /home/jcala/jmooc/log/server_log
        pattern: combined
        enabled: true
    undertow:
        io-threads: 4
        worker-threads: 10
        buffer-size: 16384
        accesslog:
            enabled: true
            dir: /home/jcala/jmooc/log/server_log
            pattern: combined
logging:
    config: classpath:log4j2.xml
spring:
    freemarker:
      enabled: true
      suffix: ftl
      charset: UTF-8
    thymeleaf:
      enabled: false
      cache: false
      encoding: utf-8
      suffix: .html
      mode: HTML5
    http:
        encoding.charset: UTF-8
        encoding.force: false
        multipart:
          max-file-size: 3MB
          max-request-size: 10MB
    cache:
        cache-names: ehcache
        ehcache:
            config: ehcache.xml
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        username: root
        password: root
        url: jdbc:mysql://127.0.0.1:3306/jmooc?serverTimezone=UTC&characterEncoding=utf-8
        driverClassName: com.mysql.cj.jdbc.Driver
        schema: classpath:import.sql
        initialize: false
        sql-script-encoding: UTF-8
        druid:
            max-active: 10
            initial-size: 3
            min-idle: 3
            max-wait: 60000
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            poolPreparedStatements: true
            maxPoolPreparedStatementPerConnectionSize: 20